/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithSidebarRouteImport } from './routes/_withSidebar'
import { Route as WithSidebarIndexRouteImport } from './routes/_withSidebar.index'
import { Route as WithSidebarListListIdRouteImport } from './routes/_withSidebar.list.$listId'

const WithSidebarRoute = WithSidebarRouteImport.update({
  id: '/_withSidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const WithSidebarIndexRoute = WithSidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithSidebarRoute,
} as any)
const WithSidebarListListIdRoute = WithSidebarListListIdRouteImport.update({
  id: '/list/$listId',
  path: '/list/$listId',
  getParentRoute: () => WithSidebarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WithSidebarIndexRoute
  '/list/$listId': typeof WithSidebarListListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof WithSidebarIndexRoute
  '/list/$listId': typeof WithSidebarListListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_withSidebar': typeof WithSidebarRouteWithChildren
  '/_withSidebar/': typeof WithSidebarIndexRoute
  '/_withSidebar/list/$listId': typeof WithSidebarListListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/list/$listId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/list/$listId'
  id:
    | '__root__'
    | '/_withSidebar'
    | '/_withSidebar/'
    | '/_withSidebar/list/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WithSidebarRoute: typeof WithSidebarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_withSidebar': {
      id: '/_withSidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_withSidebar/': {
      id: '/_withSidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithSidebarIndexRouteImport
      parentRoute: typeof WithSidebarRoute
    }
    '/_withSidebar/list/$listId': {
      id: '/_withSidebar/list/$listId'
      path: '/list/$listId'
      fullPath: '/list/$listId'
      preLoaderRoute: typeof WithSidebarListListIdRouteImport
      parentRoute: typeof WithSidebarRoute
    }
  }
}

interface WithSidebarRouteChildren {
  WithSidebarIndexRoute: typeof WithSidebarIndexRoute
  WithSidebarListListIdRoute: typeof WithSidebarListListIdRoute
}

const WithSidebarRouteChildren: WithSidebarRouteChildren = {
  WithSidebarIndexRoute: WithSidebarIndexRoute,
  WithSidebarListListIdRoute: WithSidebarListListIdRoute,
}

const WithSidebarRouteWithChildren = WithSidebarRoute._addFileChildren(
  WithSidebarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WithSidebarRoute: WithSidebarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
